[package]
name = "rpi-led-matrix"
description = "Bindings for Hzeller's RPi-RGB-Led-Matrix"
version = "0.1.2"
authors = [
    "Vincent Pasquier <vincentpasquier@posteo.net>",
    "Tyler Holmes <tyler@holmesengineering.com>",
]
repository = "https://github.com/rust-rpi-led-matrix/rust-rpi-rgb-led-matrix"
homepage = "https://github.com/rust-rpi-led-matrix/rust-rpi-rgb-led-matrix"
build = "build.rs"
license = "GPL-3.0"
readme = "README.md"

[build-dependencies]
gcc = "0.3"

[dependencies]
libc = "0.2"
